// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfTd3Hxub24q4ulIsOM4sndcEnnMr7WS8',
    appId: '1:447439811460:web:87410b4a079504b07063d1',
    messagingSenderId: '447439811460',
    projectId: 'arise-e4f21',
    authDomain: 'arise-e4f21.firebaseapp.com',
    storageBucket: 'arise-e4f21.firebasestorage.app',
    measurementId: 'G-9PSNP9KG6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5YLY8MhrTUC0sH_ewIHo2nL-lNxTjYc',
    appId: '1:447439811460:android:ae41d4c6ef7d2b947063d1',
    messagingSenderId: '447439811460',
    projectId: 'arise-e4f21',
    storageBucket: 'arise-e4f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXE5qlTmaat3Pg-Dr7F6F2adUTG-ZHbw4',
    appId: '1:447439811460:ios:b27ff016b107ef2e7063d1',
    messagingSenderId: '447439811460',
    projectId: 'arise-e4f21',
    storageBucket: 'arise-e4f21.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXE5qlTmaat3Pg-Dr7F6F2adUTG-ZHbw4',
    appId: '1:447439811460:ios:b27ff016b107ef2e7063d1',
    messagingSenderId: '447439811460',
    projectId: 'arise-e4f21',
    storageBucket: 'arise-e4f21.firebasestorage.app',
    iosBundleId: 'com.example.mobileFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfTd3Hxub24q4ulIsOM4sndcEnnMr7WS8',
    appId: '1:447439811460:web:4f86df377889cbe07063d1',
    messagingSenderId: '447439811460',
    projectId: 'arise-e4f21',
    authDomain: 'arise-e4f21.firebaseapp.com',
    storageBucket: 'arise-e4f21.firebasestorage.app',
    measurementId: 'G-GQS6J7HB5N',
  );
}
